# Generated by Django 2.1.4 on 2018-12-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200)),
                ('event_category', models.CharField(max_length=200)),
                ('event_text', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField(verbose_name='due date')),
                ('expected_date', models.DateTimeField(verbose_name='date expected')),
                ('is_finished', models.BooleanField()),
            ],
        ),
    ]
